language: bash
services: docker

env:
  - VERSION=10-jre
  - VERSION=10-jre VARIANT=slim
  - VERSION=10-jdk
  - VERSION=10-jdk VARIANT=slim
  - VERSION=9-jre
  - VERSION=9-jre VARIANT=slim
  - VERSION=9-jdk
  - VERSION=9-jdk VARIANT=slim
  - VERSION=8-jre
  - VERSION=8-jre VARIANT=slim
  - VERSION=8-jre VARIANT=alpine
  - VERSION=8-jdk
  - VERSION=8-jdk VARIANT=slim
  - VERSION=8-jdk VARIANT=alpine
  - VERSION=7-jre
  - VERSION=7-jre VARIANT=slim
  - VERSION=7-jre VARIANT=alpine
  - VERSION=7-jdk
  - VERSION=7-jdk VARIANT=slim
  - VERSION=7-jdk VARIANT=alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "${VERSION}${VARIANT:+/$VARIANT}"
  - image="openjdk:${VERSION}${VARIANT:+-$VARIANT}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
