language: bash
services: docker

env:
  - VERSION=openjdk-9-jre
  - VERSION=openjdk-9-jdk
  - VERSION=openjdk-8-jre VARIANT=alpine
  - VERSION=openjdk-8-jdk VARIANT=alpine
  - VERSION=openjdk-8-jre
  - VERSION=openjdk-8-jdk
  - VERSION=openjdk-7-jre
  - VERSION=openjdk-7-jdk
  - VERSION=openjdk-6-jre
  - VERSION=openjdk-6-jdk

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "${VERSION}${VARIANT:+-$VARIANT}"
  - image="java:${VERSION}${VARIANT:+-$VARIANT}"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
